services:
  - type: web
    name: brfantasy
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"
    autoDeploy: true

cronJobs:
  - name: daily-stats-job
    schedule: "0 5 * * *"   # Run every day at 5:00AM UTC (~midnight ET in standard time)
    command: "python cron_daily.py"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"
